name: bengali-grapheme
channels:
  - anaconda
  - conda-forge
  - defaults
dependencies:
  - _tflow_select=2.1.0
  - abseil-cpp=20210324.0
  - absl-py=0.12.0
  - aiohttp=3.7.4
  - altair=4.1.0
  - argh=0.26.2
  - argon2-cffi=20.1.0
  - arrow-cpp=4.0.0
  - astor=0.8.1
  - async-timeout=3.0.1
  - async_generator=1.10
  - attrs=20.3.0
  - aws-c-cal=0.5.7
  - aws-c-common=0.5.11
  - aws-c-event-stream=0.2.7
  - aws-c-io=0.9.11
  - aws-checksums=0.1.11
  - aws-sdk-cpp=1.8.186
  - backcall=0.2.0
  - base58=2.1.0
  - blas=1.0
  - bleach=3.2.1
  - blinker=1.4
  - boto3=1.17.69
  - botocore=1.20.69
  - brotli=1.0.9
  - brotlipy=0.7.0
  - bzip2=1.0.8
  - c-ares=1.17.1
  - ca-certificates=2020.12.5
  - cachetools=4.2.2
  - certifi=2020.12.5
  - cffi=1.14.5
  - chardet=3.0.4
  - click=7.1.2
  - colorama=0.4.4
  - coverage=5.5
  - cramjam=2.3.0
  - cryptography=3.4.7
  - cudatoolkit=10.1.243
  - cudnn=7.6.5
  - cycler=0.10.0
  - cython=0.29.23
  - decorator=4.4.2
  - defusedxml=0.6.0
  - entrypoints=0.3
  - fastparquet=0.6.0
  - freeglut=3.2.1
  - freetype=2.10.4
  - gast=0.2.2
  - gflags=2.2.2
  - gitdb=4.0.7
  - gitpython=3.1.15
  - glog=0.4.0
  - google-auth=1.30.0
  - google-auth-oauthlib=0.4.4
  - google-pasta=0.2.0
  - grpc-cpp=1.37.1
  - grpcio=1.36.1
  - h5py=2.10.0
  - hdf5=1.10.4
  - icu=68.1
  - idna=2.10
  - importlib-metadata=3.10.0
  - intel-openmp=2021.2.0
  - ipykernel=5.3.4
  - ipython=7.18.1
  - ipython_genutils=0.2.0
  - ipywidgets=7.5.1
  - jasper=2.0.14
  - jedi=0.18.0
  - jinja2=2.11.2
  - jmespath=0.10.0
  - joblib=1.0.1
  - jpeg=9d
  - jsonschema=3.0.2
  - jupyter=1.0.0
  - jupyter_client=6.1.7
  - jupyter_console=6.2.0
  - jupyter_core=4.6.3
  - jupyterlab_pygments=0.1.2
  - keras-applications=1.0.8
  - keras-preprocessing=1.1.2
  - kiwisolver=1.3.1
  - krb5=1.17.2
  - lcms2=2.12
  - libblas=3.9.0
  - libcblas=3.9.0
  - libclang=11.1.0
  - libcurl=7.76.1
  - liblapack=3.9.0
  - liblapacke=3.9.0
  - libopencv=4.5.2
  - libpng=1.6.37
  - libprotobuf=3.15.8
  - libsodium=1.0.18
  - libssh2=1.9.0
  - libthrift=0.14.1
  - libtiff=4.2.0
  - libutf8proc=2.6.1
  - libwebp-base=1.2.0
  - llvmlite=0.36.0
  - lz4-c=1.9.3
  - markdown=3.3.4
  - markupsafe=1.1.1
  - matplotlib=3.4.1
  - matplotlib-base=3.4.1
  - mistune=0.8.4
  - mkl=2021.2.0
  - mkl-service=2.3.0
  - mkl_fft=1.3.0
  - mkl_random=1.2.1
  - multidict=5.1.0
  - nbclient=0.5.1
  - nbconvert=6.0.7
  - nbformat=5.0.8
  - nest-asyncio=1.4.1
  - notebook=6.1.4
  - numba=0.53.1
  - numpy=1.20.2
  - oauthlib=3.1.0
  - olefile=0.46
  - opencv=4.5.2
  - openjpeg=2.4.0
  - openssl=1.1.1k
  - opt_einsum=3.1.0
  - packaging=20.4
  - pandas=1.2.4
  - pandoc=2.11
  - pandocfilters=1.4.2
  - parquet-cpp=1.5.1
  - parso=0.8.0
  - pickleshare=0.7.5
  - pillow=8.1.2
  - pip=21.0.1
  - prometheus_client=0.8.0
  - prompt-toolkit=3.0.8
  - prompt_toolkit=3.0.8
  - protobuf=3.15.8
  - py-opencv=4.5.2
  - pyarrow=4.0.0
  - pyasn1=0.4.8
  - pyasn1-modules=0.2.8
  - pycparser=2.20
  - pydeck=0.6.2
  - pygments=2.7.1
  - pyjwt=1.7.1
  - pyopenssl=20.0.1
  - pyparsing=2.4.7
  - pyqt=5.12.3
  - pyqt-impl=5.12.3
  - pyqt5-sip=4.19.18
  - pyqtchart=5.12
  - pyqtwebengine=5.12.1
  - pyrsistent=0.17.3
  - pysocks=1.7.1
  - python=3.7.10
  - python-dateutil=2.8.1
  - python_abi=3.7
  - pytz=2021.1
  - pyyaml=5.4.1
  - pyzmq=19.0.2
  - qt=5.12.9
  - qtconsole=4.7.7
  - qtpy=1.9.0
  - re2=2021.04.01
  - requests=2.25.1
  - requests-oauthlib=1.3.0
  - rsa=4.7.2
  - s3transfer=0.4.2
  - scikit-learn=0.24.2
  - scipy=1.6.2
  - seaborn=0.11.0
  - send2trash=1.5.0
  - setuptools=52.0.0
  - sip=4.19.24
  - six=1.15.0
  - smmap=3.0.5
  - snappy=1.1.8
  - sqlite=3.35.4
  - streamlit=0.81.1
  - tensorboard=2.4.0
  - tensorboard-plugin-wit=1.6.0
  - tensorflow=2.1.0
  - tensorflow-base=2.1.0
  - tensorflow-estimator=2.1.0
  - tensorflow-gpu=2.1.0
  - termcolor=1.1.0
  - terminado=0.9.1
  - testpath=0.4.4
  - threadpoolctl=2.1.0
  - thrift=0.13.0
  - tk=8.6.10
  - toml=0.10.2
  - toolz=0.11.1
  - tornado=6.0.4
  - tqdm=4.60.0
  - traitlets=5.0.5
  - typing-extensions=3.7.4.3
  - typing_extensions=3.7.4.3
  - tzlocal=2.1
  - urllib3=1.26.4
  - validators=0.18.2
  - watchdog=2.1.0
  - wcwidth=0.2.5
  - webencodings=0.5.1
  - werkzeug=0.16.1
  - wheel=0.36.2
  - widgetsnbextension=3.5.1
  - wrapt=1.12.1
  - xz=5.2.5
  - yaml=0.2.5
  - yarl=1.6.3
  - zeromq=4.3.2
  - zipp=3.4.1
  - zlib=1.2.11
  - zstd=1.4.9
